services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "3005:3000"
      - "5555:5555"
    depends_on:
      - "db"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3001:3001"
  db:
    image: ankane/pgvector:v0.5.1
    ports:
      - 5435:5432
    volumes:
      - type: bind
        source: ./api/db-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=doc_db
networks:
  local: {}
